### ISSUE TITLE
Gem Conflict when invoking jarbs 0.6.2

### ISSUE THREAD

**Issue by chazu** [articulate/jarbs#12]
```
┐ (Chazu@Nono) [10:54:42|Mon Jan 04] [REDACTED]
└───> jarbs
/Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate sawyer-0.6.0, because addressable-2.4.0 conflicts with addressable (~> 2.3.5) (Gem::ConflictError)
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.2/lib/jarbs/github_auth.rb:1:in `<top (required)>'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.2/lib/jarbs.rb:10:in `<top (required)>'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/Chazu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.2/bin/jarbs:7:in `<top (required)>'
	from /Users/Chazu/.rbenv/versions/2.2.0/bin/jarbs:23:in `load'
	from /Users/Chazu/.rbenv/versions/2.2.0/bin/jarbs:23:in `<main>'
```

**Comment by plukevdh** [comment]
@chazu any specific command or any?

**Comment by chazu** [comment]
Any of 'em. :/

**Comment by chazu** [comment]
Fixed this by just uninstalling all the things (addressable) and reinstalling jarbs. Works fine. Closing the issue since its just an inconvenience at worst, presently.

**Comment by plukevdh** [comment]
Must be a global gem install conflict. Still, that seems like a Bad Thing™. Probably residuals of using RubyGems to distribute vs. using a more isolated distro method. Something to be done in the future. Thanks for the feedback.
