### ISSUE TITLE
Crash report from airbrake_lambda

### ISSUE THREAD

**Issue by adferras** [articulate/jarbs#9]
**Error:** 1 validation error detected: Value 'lambda_basic_execution' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+

**Backtrace:**
```
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/request.rb:70:in `send_request'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/lib/jarbs/lambda.rb:50:in `block in create'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/crash-reporter-0.1.1/lib/crash_reporter/dsl.rb:31:in `capture_errors'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/lib/jarbs/lambda.rb:49:in `create'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/lib/jarbs/lambda.rb:41:in `deploy'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/lib/jarbs.rb:117:in `block (2 levels) in run'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/lib/jarbs.rb:173:in `run'
/Users/adamferras/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jarbs-0.6.1/bin/jarbs:9:in `<top (required)>'
/Users/adamferras/.rbenv/versions/2.2.0/bin/jarbs:23:in `load'
/Users/adamferras/.rbenv/versions/2.2.0/bin/jarbs:23:in `<main>'
```

**Comment by plukevdh** [comment]
@adferras you got this figured out?

**Comment by adferras** [comment]
Correct.  Sorry about that.  This was a part of my testing and documentation process.

**Comment by plukevdh** [comment]
No worries. Nice to know this is working.
